server :
  port: 8888
  logging:
    level:
      org.spring.framework.web: DEBUG

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: jozinho
  resource: brazil-demo-app
  ssl-required: external
  public-client: true
  use-resource-role-mappings: true
  #securityConstraints[0].authRoles[0]: user